cmake_minimum_required(VERSION 2.8)
project(happyhttp)
file(GLOB_RECURSE SOURCES happyhttp.c happyhttp.cpp happyhttp.cc happyhttp.cxx)
file(GLOB_RECURSE HEADERS happyhttp.h happyhttp.hpp happyhttp.hh happyhttp.hxx)
add_library(happyhttp ${SOURCES})
if(WIN32)
    target_link_libraries(happyhttp ws2_32)
endif()
install(TARGETS happyhttp DESTINATION lib)
install(FILES ${HEADERS} DESTINATION include)
