cmake_minimum_required(VERSION 2.8)

if(BUILD_SHARED_LIBS)
    set(USE_STATIC_MBEDTLS_LIBRARY Off CACHE BOOL "")
    set(USE_SHARED_MBEDTLS_LIBRARY On CACHE BOOL "")
else()
    set(USE_STATIC_MBEDTLS_LIBRARY On CACHE BOOL "")
    set(USE_SHARED_MBEDTLS_LIBRARY Off CACHE BOOL "")
endif()

include(${CGET_CMAKE_ORIGINAL_SOURCE_FILE})
